<?php

#----------------------------------------------------------------------#
#   CODED BY: Avin-Knight                                              #
#   GATE: FLAGs GENERATOR                                              #
#----------------------------------------------------------------------#

error_reporting(0);
ini_set('display_errors', 0);
date_default_timezone_set('America/Buenos_Aires');



////==============[ FLAGs GENERATOR ]==============////

function getFlags($code){
    $code = strtoupper($code);
    if(($code == 'AD') || ($code == 'AND')) return '🇦🇩';
    if(($code == 'AE') || ($code == 'ARE')) return '🇦🇪';
    if(($code == 'AF') || ($code == 'AFG')) return '🇦🇫';
    if(($code == 'AG') || ($code == 'ATG')) return '🇦🇬';
    if(($code == 'AI') || ($code == 'AIA')) return '🇦🇮';
    if(($code == 'AL') || ($code == 'ALB')) return '🇦🇱';
    if(($code == 'AM') || ($code == 'ARM')) return '🇦🇲';
    if(($code == 'AO') || ($code == 'AGO')) return '🇦🇴';
    if(($code == 'AQ') || ($code == 'ATA')) return '🇦🇶';
    if(($code == 'AR') || ($code == 'ARG')) return '🇦🇷';
    if(($code == 'AS') || ($code == 'ASM')) return '🇦🇸';
    if(($code == 'AT') || ($code == 'AUT')) return '🇦🇹';
    if(($code == 'AU') || ($code == 'AUS')) return '🇦🇺';
    if(($code == 'AW') || ($code == 'ABW')) return '🇦🇼';
    if(($code == 'AX') || ($code == 'ALA')) return '🇦🇽';
    if(($code == 'AZ') || ($code == 'AZE')) return '🇦🇿';
    if(($code == 'BA') || ($code == 'BIH')) return '🇧🇦';
    if(($code == 'BB') || ($code == 'BRB')) return '🇧🇧';
    if(($code == 'BD') || ($code == 'BGD')) return '🇧🇩';
    if(($code == 'BE') || ($code == 'BEL')) return '🇧🇪';
    if(($code == 'BF') || ($code == 'BFA')) return '🇧🇫';
    if(($code == 'BG') || ($code == 'BGR')) return '🇧🇬';
    if(($code == 'BH') || ($code == 'BHR')) return '🇧🇭';
    if(($code == 'BI') || ($code == 'BDI')) return '🇧🇮';
    if(($code == 'BJ') || ($code == 'BEN')) return '🇧🇯';
    if(($code == 'BL') || ($code == 'BLM')) return '🇧🇱';
    if(($code == 'BM') || ($code == 'BMU')) return '🇧🇲';
    if(($code == 'BN') || ($code == 'BRN')) return '🇧🇳';
    if(($code == 'BO') || ($code == 'BOL')) return '🇧🇴';
    if(($code == 'BQ') || ($code == 'BES')) return '🇧🇶';
    if(($code == 'BR') || ($code == 'BRA')) return '🇧🇷';
    if(($code == 'BS') || ($code == 'BHS')) return '🇧🇸';
    if(($code == 'BT') || ($code == 'BTN')) return '🇧🇹';
    if(($code == 'BV') || ($code == 'BVT')) return '🇧🇻';
    if(($code == 'BW') || ($code == 'BWA')) return '🇧🇼';
    if(($code == 'BY') || ($code == 'BLR')) return '🇧🇾';
    if(($code == 'BZ') || ($code == 'BLZ')) return '🇧🇿';
    if(($code == 'CA') || ($code == 'CAN')) return '🇨🇦';
    if(($code == 'CC') || ($code == 'CCK')) return '🇨🇨';
    if(($code == 'CD') || ($code == 'COD')) return '🇨🇩';
    if(($code == 'CF') || ($code == 'CAF')) return '🇨🇫';
    if(($code == 'CG') || ($code == 'COG')) return '🇨🇬';
    if(($code == 'CH') || ($code == 'CHE')) return '🇨🇭';
    if(($code == 'CI') || ($code == 'CIV')) return '🇨🇮';
    if(($code == 'CK') || ($code == 'COK')) return '🇨🇰';
    if(($code == 'CL') || ($code == 'CHL')) return '🇨🇱';
    if(($code == 'CM') || ($code == 'CMR')) return '🇨🇲';
    if(($code == 'CN') || ($code == 'CHN')) return '🇨🇳';
    if(($code == 'CO') || ($code == 'COL')) return '🇨🇴';
    if(($code == 'CR') || ($code == 'CRI')) return '🇨🇷';
    if(($code == 'CU') || ($code == 'CUB')) return '🇨🇺';
    if(($code == 'CV') || ($code == 'CPV')) return '🇨🇻';
    if(($code == 'CW') || ($code == 'CUW')) return '🇨🇼';
    if(($code == 'CX') || ($code == 'CXR')) return '🇨🇽';
    if(($code == 'CY') || ($code == 'CYP')) return '🇨🇾';
    if(($code == 'CZ') || ($code == 'CZE')) return '🇨🇿';
    if(($code == 'DE') || ($code == 'DEU')) return '🇩🇪';
    if(($code == 'DJ') || ($code == 'DJI')) return '🇩🇯';
    if(($code == 'DK') || ($code == 'DNK')) return '🇩🇰';
    if(($code == 'DM') || ($code == 'DMA')) return '🇩🇲';
    if(($code == 'DO') || ($code == 'DOM')) return '🇩🇴';
    if(($code == 'DZ') || ($code == 'DZA')) return '🇩🇿';
    if(($code == 'EC') || ($code == 'ECU')) return '🇪🇨';
    if(($code == 'EE') || ($code == 'EST')) return '🇪🇪';
    if(($code == 'EG') || ($code == 'EGY')) return '🇪🇬';
    if(($code == 'EH') || ($code == 'ESH')) return '🇪🇭';
    if(($code == 'ER') || ($code == 'ERI')) return '🇪🇷';
    if(($code == 'ES') || ($code == 'ESP')) return '🇪🇸';
    if(($code == 'ET') || ($code == 'ETH')) return '🇪🇹';
    if(($code == 'FI') || ($code == 'FIN')) return '🇫🇮';
    if(($code == 'FJ') || ($code == 'FJI')) return '🇫🇯';
    if(($code == 'FK') || ($code == 'FLK')) return '🇫🇰';
    if(($code == 'FM') || ($code == 'FSM')) return '🇫🇲';
    if(($code == 'FO') || ($code == 'FRO')) return '🇫🇴';
    if(($code == 'FR') || ($code == 'FRA')) return '🇫🇷';
    if(($code == 'GA') || ($code == 'GAB')) return '🇬🇦';
    if(($code == 'GB') || ($code == 'GBR')) return '🇬🇧';
    if(($code == 'GD') || ($code == 'GRD')) return '🇬🇩';
    if(($code == 'GE') || ($code == 'GEO')) return '🇬🇪';
    if(($code == 'GF') || ($code == 'GUF')) return '🇬🇫';
    if(($code == 'GG') || ($code == 'GGY')) return '🇬🇬';
    if(($code == 'GH') || ($code == 'GHA')) return '🇬🇭';
    if(($code == 'GI') || ($code == 'GIB')) return '🇬🇮';
    if(($code == 'GL') || ($code == 'GRL')) return '🇬🇱';
    if(($code == 'GM') || ($code == 'GMB')) return '🇬🇲';
    if(($code == 'GN') || ($code == 'GIN')) return '🇬🇳';
    if(($code == 'GP') || ($code == 'GLP')) return '🇬🇵';
    if(($code == 'GQ') || ($code == 'GNQ')) return '🇬🇶';
    if(($code == 'GR') || ($code == 'GRC')) return '🇬🇷';
    if(($code == 'GS') || ($code == 'SGS')) return '🇬🇸';
    if(($code == 'GT') || ($code == 'GTM')) return '🇬🇹';
    if(($code == 'GU') || ($code == 'GUM')) return '🇬🇺';
    if(($code == 'GW') || ($code == 'GNB')) return '🇬🇼';
    if(($code == 'GY') || ($code == 'GUY')) return '🇬🇾';
    if(($code == 'HK') || ($code == 'HKG')) return '🇭🇰';
    if(($code == 'HM') || ($code == 'HMD')) return '🇭🇲';
    if(($code == 'HN') || ($code == 'HND')) return '🇭🇳';
    if(($code == 'HR') || ($code == 'HRV')) return '🇭🇷';
    if(($code == 'HT') || ($code == 'HTI')) return '🇭🇹';
    if(($code == 'HU') || ($code == 'HUN')) return '🇭🇺';
    if(($code == 'ID') || ($code == 'IDN')) return '🇮🇩';
    if(($code == 'IE') || ($code == 'IRL')) return '🇮🇪';
    if(($code == 'IL') || ($code == 'ISR')) return '🇮🇱';
    if(($code == 'IM') || ($code == 'IMN')) return '🇮🇲';
    if(($code == 'IN') || ($code == 'IND')) return '🇮🇳';
    if(($code == 'IO') || ($code == 'IOT')) return '🇮🇴';
    if(($code == 'IQ') || ($code == 'IRO')) return '🇮🇶';
    if(($code == 'IR') || ($code == 'IRN')) return '🇮🇷';
    if(($code == 'IS') || ($code == 'ISL')) return '🇮🇸';
    if(($code == 'IT') || ($code == 'ITA')) return '🇮🇹';
    if(($code == 'JE') || ($code == 'JEY')) return '🇯🇪';
    if(($code == 'JM') || ($code == 'JAM')) return '🇯🇲';
    if(($code == 'JO') || ($code == 'JOR')) return '🇯🇴';
    if(($code == 'JP') || ($code == 'JPN')) return '🇯🇵';
    if(($code == 'KE') || ($code == 'KEN')) return '🇰🇪';
    if(($code == 'KG') || ($code == 'KGZ')) return '🇰🇬';
    if(($code == 'KH') || ($code == 'KHM')) return '🇰🇭';
    if(($code == 'KI') || ($code == 'KIR')) return '🇰🇮';
    if(($code == 'KM') || ($code == 'COM')) return '🇰🇲';
    if(($code == 'KN') || ($code == 'KNA')) return '🇰🇳';
    if(($code == 'KP') || ($code == 'PRK')) return '🇰🇵';
    if(($code == 'KR') || ($code == 'KOR')) return '🇰🇷';
    if(($code == 'KW') || ($code == 'KWT')) return '🇰🇼';
    if(($code == 'KY') || ($code == 'CYM')) return '🇰🇾';
    if(($code == 'KZ') || ($code == 'KZA')) return '🇰🇿';
    if(($code == 'LA') || ($code == 'LAO')) return '🇱🇦';
    if(($code == 'LB') || ($code == 'LBN')) return '🇱🇧';
    if(($code == 'LC') || ($code == 'LCA')) return '🇱🇨';
    if(($code == 'LI') || ($code == 'LIE')) return '🇱🇮';
    if(($code == 'LK') || ($code == 'LKA')) return '🇱🇰';
    if(($code == 'LR') || ($code == 'LBR')) return '🇱🇷';
    if(($code == 'LS') || ($code == 'LSO')) return '🇱🇸';
    if(($code == 'LT') || ($code == 'LTU')) return '🇱🇹';
    if(($code == 'LU') || ($code == 'LUX')) return '🇱🇺';
    if(($code == 'LV') || ($code == 'LVA')) return '🇱🇻';
    if(($code == 'LY') || ($code == 'LBY')) return '🇱🇾';
    if(($code == 'MA') || ($code == 'MAR')) return '🇲🇦';
    if(($code == 'MC') || ($code == 'MCO')) return '🇲🇨';
    if(($code == 'MD') || ($code == 'MDA')) return '🇲🇩';
    if(($code == 'ME') || ($code == 'MNE')) return '🇲🇪';
    if(($code == 'MF') || ($code == 'MAF')) return '🇲🇫';
    if(($code == 'MG') || ($code == 'MDG')) return '🇲🇬';
    if(($code == 'MH') || ($code == 'MHL')) return '🇲🇭';
    if(($code == 'MK') || ($code == 'MKD')) return '🇲🇰';
    if(($code == 'ML') || ($code == 'MLI')) return '🇲🇱';
    if(($code == 'MM') || ($code == 'MMR')) return '🇲🇲';
    if(($code == 'MN') || ($code == 'MNG')) return '🇲🇳';
    if(($code == 'MO') || ($code == 'MAC')) return '🇲🇴';
    if(($code == 'MP') || ($code == 'MNP')) return '🇲🇵';
    if(($code == 'MQ') || ($code == 'MTQ')) return '🇲🇶';
    if(($code == 'MR') || ($code == 'MRT')) return '🇲🇷';
    if(($code == 'MS') || ($code == 'MSR')) return '🇲🇸';
    if(($code == 'MT') || ($code == 'MLT')) return '🇲🇹';
    if(($code == 'MU') || ($code == 'MUS')) return '🇲🇺';
    if(($code == 'MV') || ($code == 'MDV')) return '🇲🇻';
    if(($code == 'MW') || ($code == 'MWI')) return '🇲🇼';
    if(($code == 'MX') || ($code == 'MEX')) return '🇲🇽';
    if(($code == 'MY') || ($code == 'MYS')) return '🇲🇾';
    if(($code == 'MZ') || ($code == 'MOZ')) return '🇲🇿';
    if(($code == 'NA') || ($code == 'NAM')) return '🇳🇦';
    if(($code == 'NC') || ($code == 'NCL')) return '🇳🇨';
    if(($code == 'NE') || ($code == 'NER')) return '🇳🇪';
    if(($code == 'NF') || ($code == 'NFK')) return '🇳🇫';
    if(($code == 'NG') || ($code == 'NGA')) return '🇳🇬';
    if(($code == 'NI') || ($code == 'NIC')) return '🇳🇮';
    if(($code == 'NL') || ($code == 'NLD')) return '🇳🇱';
    if(($code == 'NO') || ($code == 'NOR')) return '🇳🇴';
    if(($code == 'NP') || ($code == 'NPL')) return '🇳🇵';
    if(($code == 'NR') || ($code == 'NRU')) return '🇳🇷';
    if(($code == 'NU') || ($code == 'NIU')) return '🇳🇺';
    if(($code == 'NZ') || ($code == 'NZL')) return '🇳🇿';
    if(($code == 'OM') || ($code == 'OMN')) return '🇴🇲';
    if(($code == 'PA') || ($code == 'PAN')) return '🇵🇦';
    if(($code == 'PE') || ($code == 'PER')) return '🇵🇪';
    if(($code == 'PF') || ($code == 'PYF')) return '🇵🇫';
    if(($code == 'PG') || ($code == 'PNG')) return '🇵🇬';
    if(($code == 'PH') || ($code == 'PHL')) return '🇵🇭';
    if(($code == 'PK') || ($code == 'PAK')) return '🇵🇰';
    if(($code == 'PL') || ($code == 'POL')) return '🇵🇱';
    if(($code == 'PM') || ($code == 'SPM')) return '🇵🇲';
    if(($code == 'PN') || ($code == 'PCN')) return '🇵🇳';
    if(($code == 'PR') || ($code == 'PRI')) return '🇵🇷';
    if(($code == 'PS') || ($code == 'PSE')) return '🇵🇸';
    if(($code == 'PT') || ($code == 'PRT')) return '🇵🇹';
    if(($code == 'PW') || ($code == 'PLW')) return '🇵🇼';
    if(($code == 'PY') || ($code == 'PRY')) return '🇵🇾';
    if(($code == 'QA') || ($code == 'QAT')) return '🇶🇦';
    if(($code == 'RE') || ($code == 'REU')) return '🇷🇪';
    if(($code == 'RO') || ($code == 'ROU')) return '🇷🇴';
    if(($code == 'RS') || ($code == 'SRB')) return '🇷🇸';
    if(($code == 'RU') || ($code == 'RUS')) return '🇷🇺';
    if(($code == 'RW') || ($code == 'RWA')) return '🇷🇼';
    if(($code == 'SA') || ($code == 'SAU')) return '🇸🇦';
    if(($code == 'SB') || ($code == 'SLB')) return '🇸🇧';
    if(($code == 'SC') || ($code == 'SYC')) return '🇸🇨';
    if(($code == 'SD') || ($code == 'SDN')) return '🇸🇩';
    if(($code == 'SE') || ($code == 'SWE')) return '🇸🇪';
    if(($code == 'SG') || ($code == 'SGP')) return '🇸🇬';
    if(($code == 'SH') || ($code == 'SHN')) return '🇸🇭';
    if(($code == 'SI') || ($code == 'SVN')) return '🇸🇮';
    if(($code == 'SJ') || ($code == 'SJM')) return '🇸🇯';
    if(($code == 'SK') || ($code == 'SVK')) return '🇸🇰';
    if(($code == 'SL') || ($code == 'SLE')) return '🇸🇱';
    if(($code == 'SM') || ($code == 'SMR')) return '🇸🇲';
    if(($code == 'SN') || ($code == 'SEN')) return '🇸🇳';
    if(($code == 'SO') || ($code == 'SOM')) return '🇸🇴';
    if(($code == 'SR') || ($code == 'SUR')) return '🇸🇷';
    if(($code == 'SS') || ($code == 'SSD')) return '🇸🇸';
    if(($code == 'ST') || ($code == 'STP')) return '🇸🇹';
    if(($code == 'SV') || ($code == 'SLV')) return '🇸🇻';
    if(($code == 'SX') || ($code == 'SXM')) return '🇸🇽';
    if(($code == 'SY') || ($code == 'SYR')) return '🇸🇾';
    if(($code == 'SZ') || ($code == 'SWZ')) return '🇸🇿';
    if(($code == 'TC') || ($code == 'TCA')) return '🇹🇨';
    if(($code == 'TD') || ($code == 'TCD')) return '🇹🇩';
    if(($code == 'TF') || ($code == 'ATF')) return '🇹🇫';
    if(($code == 'TG') || ($code == 'TGO')) return '🇹🇬';
    if(($code == 'TH') || ($code == 'THA')) return '🇹🇭';
    if(($code == 'TJ') || ($code == 'TJK')) return '🇹🇯';
    if(($code == 'TK') || ($code == 'TKL')) return '🇹🇰';
    if(($code == 'TL') || ($code == 'TLS')) return '🇹🇱';
    if(($code == 'TM') || ($code == 'TKM')) return '🇹🇲';
    if(($code == 'TN') || ($code == 'TUN')) return '🇹🇳';
    if(($code == 'TO') || ($code == 'TON')) return '🇹🇴';
    if(($code == 'TR') || ($code == 'TUR')) return '🇹🇷';
    if(($code == 'TT') || ($code == 'TTO')) return '🇹🇹';
    if(($code == 'TV') || ($code == 'TUV')) return '🇹🇻';
    if(($code == 'TW') || ($code == 'TWN')) return '🇹🇼';
    if(($code == 'TZ') || ($code == 'TZA')) return '🇹🇿';
    if(($code == 'UA') || ($code == 'UKR')) return '🇺🇦';
    if(($code == 'UG') || ($code == 'UGA')) return '🇺🇬';
    if(($code == 'UM') || ($code == 'UMI')) return '🇺🇲';
    if(($code == 'US') || ($code == 'USA')) return '🇺🇸';
    if(($code == 'UY') || ($code == 'URY')) return '🇺🇾';
    if(($code == 'UZ') || ($code == 'UZB')) return '🇺🇿';
    if(($code == 'VA') || ($code == 'VAT')) return '🇻🇦';
    if(($code == 'VC') || ($code == 'VCT')) return '🇻🇨';
    if(($code == 'VE') || ($code == 'VEN')) return '🇻🇪';
    if(($code == 'VG') || ($code == 'VGB')) return '🇻🇬';
    if(($code == 'VI') || ($code == 'VIR')) return '🇻🇮';
    if(($code == 'VN') || ($code == 'VNM')) return '🇻🇳';
    if(($code == 'VU') || ($code == 'VUT')) return '🇻🇺';
    if(($code == 'WF') || ($code == 'WLF')) return '🇼🇫';
    if(($code == 'WS') || ($code == 'WSM')) return '🇼🇸';
    if(($code == 'XK') || ($code == 'XKX')) return '🇽🇰';
    if(($code == 'YE') || ($code == 'YEM')) return '🇾🇪';
    if(($code == 'YT') || ($code == 'MYT')) return '🇾🇹';
    if(($code == 'ZA') || ($code == 'ZAF')) return '🇿🇦';
    if(($code == 'ZM') || ($code == 'ZMB')) return '🇿🇲';
    return '🏳';
}


////=============[Bin Command-END]==============////





?>